### ISSUE TITLE
Push images into a Docker Hub repository

### ISSUE THREAD

**Issue by calebespinoza** [bc-lt-at-fs-03-devops/banking-api#15]
As a operator, I need to store every new stable container image built with the latest changes in the app's source code, which will help me to deploy the app in different environments.

**Acceptance Criteria**
-
- A new public/private repo should be created in a Docker Hub account.
- A Personal Access Token should be used to login to the Docker Hub account through `docker login`.
- The new image should be tag with a incremental numeric version.
- The new image should be stored in the repo properly.

**Sources**
-
* [docker push](https://docs.docker.com/engine/reference/commandline/push/)
* [docker login](https://docs.docker.com/engine/reference/commandline/login/)

**Deadline**
-
Tuesday 7th, 2023

**Comment by kevingaray** [comment]
# Steps
1. Create and save docker [access token](https://docs.docker.com/docker-hub/access-tokens/)  
2. Login `docker login --username <username>` , the password is the access token
3. [Push new image to registry](https://docs.docker.com/engine/reference/commandline/push/#push-a-new-image-to-a-registry)
3.1. Save new image by finding container id `docker container ls`
`docker container commit COMMIT-ID bank-api:1.0.0`
3.2. Tag image (change kevingerardo23 to username)
`docker image tag bank-api:1.0.0 kevingerardo23/bank-api:1.0.0`
3.3. Push image
`docker image push kevingerardo23/bank-api:1.0.0`

**Help resources:**
[ Problem : "requested access to the resource is denied"](https://stackoverflow.com/questions/41984399/denied-requested-access-to-the-resource-is-denied-docker)
