### ISSUE TITLE
Run the Static Code Analysis in the CI workflow

### ISSUE THREAD

**Issue by calebespinoza** [bc-lt-at-fs-03-devops/banking-api#25]
As a developer, I need to know the code quality status in every integration. Sonarcloud is a cloud platform which can show us metrics about code smells, maintainability, code coverage, etc. This tool will help us to measure our code quality.

**Acceptance Criteria**
-
- A free, public organization and project should be created in [sonarcloud.io](https://www.sonarsource.com/products/sonarcloud/).
- The GH action [sonarcloud-scan](https://github.com/marketplace/actions/sonarcloud-scan) should be used.
- **The Code Coverage report should be sent to Sonarcloud.**
- A report with the measures should be shown in the project's dashboard in Sonarcloud.
- **IMPORTANT: None token, password or sensible data should be hardcoded in any commit**

**Sources**
-
- [Github Actions for Sonarcloud](https://docs.sonarcloud.io/advanced-setup/ci-based-analysis/github-actions-for-sonarcloud/).
- [SonarScanner CLI](https://docs.sonarcloud.io/advanced-setup/ci-based-analysis/sonarscanner-cli/)
- [Python Test Coverage](https://docs.sonarcloud.io/enriching/test-coverage/python-test-coverage/)

**Deadline**
-
Friday 10th, 2023

**Comment by Camiloarceg** [comment]
Hi @calebespinoza   just to let you know we are Blocked with tickets# 25 and 26 . We couldn't set up the sonar cloud project from github and doing some research we realized that we need to set up the project from sonar cloud first, but we don't have permissions since we are not owner, can you please accept the request to allow the sonar cloud organization get the projects on our github project?

**Comment by Camiloarceg** [comment]
Setting up the project first we obtain vital information for the configuration nedde on #25 and 26:
SONAR_TOKEN
sonar.projectKey
sonar.organization

**Comment by Camiloarceg** [comment]
UPDATE: we are not block this was a false alarm I'm sorry .
