### ISSUE TITLE
Create and provision the infrastructure for the API

### ISSUE THREAD

**Issue by calebespinoza** [bc-lt-at-fs-03-devops/banking-api#28]
As an operator, I need to provision the infrastructure where the Web UI app will be deployed.

**Acceptance Criteria**
-
- A new Ubuntu server should be created in the Cloud provider applying the constrains for the free tier.
- The server should be provisioned with Docker Engine.
- Only the ports 22 (SSH) and 8050 (TCP) should be opened for inbound traffic.
- The server should have internet connection.

**Deadline**
-
Tuesday 14th, 2023

**Comment by DMGochoa** [comment]
![Image](https://user-images.githubusercontent.com/100704377/225086895-0fbe8dfe-11ef-47ba-aeeb-be1a4cd97db4.png)

The api is deployed in a ubuntu server @calebespinoza.
